#!/usr/bin/env python3
"""
Dify Custom Nodes Mount Manager

This script sets up volume mounts or symlinks for custom nodes
in both Docker and development modes.
"""

import argparse
import os
import sys
from pathlib import Path
from typing import Optional


class Colors:
    """ANSI color codes"""
    RED = '\033[0;31m'
    GREEN = '\033[0;32m'
    YELLOW = '\033[1;33m'
    BLUE = '\033[0;34m'
    NC = '\033[0m'


def print_colored(message: str, color: str = Colors.NC):
    """Print colored message"""
    print(f"{color}{message}{Colors.NC}")


def create_symlink(source: Path, target: Path, force: bool = False) -> bool:
    """
    Create a symlink from source to target

    Args:
        source: Source directory (where files actually are)
        target: Target symlink location
        force: Remove existing target if it exists

    Returns:
        True if successful, False otherwise
    """
    try:
        # Check if target already exists
        if target.exists() or target.is_symlink():
            if target.is_symlink() and target.resolve() == source.resolve():
                print_colored(f"  ⏭️  Symlink already exists: {target} -> {source}", Colors.YELLOW)
                return True

            if force:
                print_colored(f"  🗑️  Removing existing: {target}", Colors.YELLOW)
                if target.is_dir() and not target.is_symlink():
                    import shutil
                    shutil.rmtree(target)
                else:
                    target.unlink()
            else:
                print_colored(f"  ⚠️  Target already exists: {target}", Colors.YELLOW)
                print_colored(f"     Use --force to overwrite", Colors.YELLOW)
                return False

        # Ensure parent directory exists
        target.parent.mkdir(parents=True, exist_ok=True)

        # Create symlink
        target.symlink_to(source)
        print_colored(f"  ✅ Created symlink: {target} -> {source}", Colors.GREEN)
        return True

    except Exception as e:
        print_colored(f"  ❌ Failed to create symlink: {e}", Colors.RED)
        return False


def setup_dev_mode(target_dir: Path, patcher_root: Path, force: bool = False) -> bool:
    """
    Setup symlinks for development mode

    Creates:
    - api/extensions/custom_nodes -> patcher_root/nodes
    - api/dify_custom_nodes -> patcher_root/sdk/python/dify_custom_nodes
    - web/app/components/workflow/nodes/_custom -> patcher_root/nodes
    """
    print_colored("🔗 Setting up development mode (symlinks)...", Colors.BLUE)
    print()

    success = True

    # Backend custom nodes directory
    backend_source = patcher_root / 'nodes'
    backend_target = target_dir / 'api' / 'extensions' / 'custom_nodes'

    print_colored("Backend custom nodes:", Colors.BLUE)
    if not create_symlink(backend_source, backend_target, force):
        success = False

    print()

    # Backend SDK
    sdk_source = patcher_root / 'sdk' / 'python' / 'dify_custom_nodes'
    sdk_target = target_dir / 'api' / 'dify_custom_nodes'

    print_colored("Backend SDK:", Colors.BLUE)
    if sdk_source.exists():
        if not create_symlink(sdk_source, sdk_target, force):
            success = False
    else:
        print_colored(f"  ⏭️  SDK source not found, skipping: {sdk_source}", Colors.YELLOW)

    print()

    # Frontend custom nodes directory
    frontend_source = patcher_root / 'nodes'
    frontend_target = target_dir / 'web' / 'app' / 'components' / 'workflow' / 'nodes' / '_custom'

    print_colored("Frontend custom nodes:", Colors.BLUE)
    if not create_symlink(frontend_source, frontend_target, force):
        success = False

    return success


def setup_docker_mode(target_dir: Path, patcher_root: Path) -> bool:
    """
    Setup Docker Compose override for custom nodes

    Creates docker-compose.override.yml with volume mounts
    """
    print_colored("🐳 Setting up Docker mode (docker-compose.override.yml)...", Colors.BLUE)
    print()

    docker_dir = target_dir / 'docker'
    override_file = docker_dir / 'docker-compose.override.yml'

    # Calculate relative path from docker directory to patcher root
    try:
        relative_patcher_root = os.path.relpath(patcher_root, docker_dir)
    except ValueError:
        # On Windows, if paths are on different drives
        relative_patcher_root = str(patcher_root)

    # Docker Compose override content
    override_content = f'''# Dify Custom Nodes - Auto-generated Docker Compose Override
# Generated by dify-patcher installer
#
# This file mounts custom nodes into the Dify containers.
# Do not edit manually - regenerate with: ./installer/install.sh

version: '3'

services:
  # API service - Backend custom nodes
  api:
    volumes:
      # Custom nodes (read-only for safety)
      - {relative_patcher_root}/nodes:/app/api/extensions/custom_nodes:ro
      # Python SDK (read-only)
      - {relative_patcher_root}/sdk/python/dify_custom_nodes:/app/api/dify_custom_nodes:ro
    environment:
      # Enable custom nodes
      - CUSTOM_NODES_ENABLED=true
      - CUSTOM_NODES_PATH=/app/api/extensions/custom_nodes

  # Web service - Frontend custom nodes
  web:
    volumes:
      # Custom node frontend components (read-only)
      - {relative_patcher_root}/nodes:/app/web/app/components/workflow/nodes/_custom:ro
    environment:
      # Enable custom nodes in frontend
      - NEXT_PUBLIC_CUSTOM_NODES_ENABLED=true

  # Worker service - Also needs custom nodes for task execution
  worker:
    volumes:
      # Custom nodes (read-only)
      - {relative_patcher_root}/nodes:/app/api/extensions/custom_nodes:ro
      # Python SDK (read-only)
      - {relative_patcher_root}/sdk/python/dify_custom_nodes:/app/api/dify_custom_nodes:ro
    environment:
      # Enable custom nodes
      - CUSTOM_NODES_ENABLED=true
      - CUSTOM_NODES_PATH=/app/api/extensions/custom_nodes
'''

    try:
        # Check if override file already exists
        if override_file.exists():
            print_colored(f"  ⚠️  File already exists: {override_file}", Colors.YELLOW)

            # Read existing content
            with open(override_file, 'r') as f:
                existing_content = f.read()

            # Check if it's our auto-generated file
            if 'dify-patcher installer' in existing_content:
                print_colored(f"  🔄 Updating existing override file...", Colors.BLUE)
            else:
                # Backup existing file
                backup_file = override_file.with_suffix('.yml.backup')
                print_colored(f"  📦 Backing up to: {backup_file}", Colors.YELLOW)

                with open(backup_file, 'w') as f:
                    f.write(existing_content)

        # Write override file
        with open(override_file, 'w') as f:
            f.write(override_content)

        print_colored(f"  ✅ Created: {override_file}", Colors.GREEN)
        print()
        print_colored(f"  📝 Relative path used: {relative_patcher_root}", Colors.BLUE)

        return True

    except Exception as e:
        print_colored(f"  ❌ Failed to create override file: {e}", Colors.RED)
        return False


def setup_env_file(target_dir: Path, mode: str) -> bool:
    """
    Setup or update .env file with custom nodes configuration
    """
    if mode == 'docker':
        env_file = target_dir / 'docker' / '.env'
    else:
        env_file = target_dir / '.env'

    env_content_to_add = [
        '',
        '# Custom Nodes Configuration (added by dify-patcher)',
        'CUSTOM_NODES_ENABLED=true',
    ]

    try:
        # Check if .env exists
        if env_file.exists():
            with open(env_file, 'r') as f:
                existing_content = f.read()

            # Check if already configured
            if 'CUSTOM_NODES_ENABLED' in existing_content:
                print_colored(f"  ⏭️  Custom nodes already enabled in {env_file}", Colors.YELLOW)
                return True

            # Append to existing file
            with open(env_file, 'a') as f:
                f.write('\n'.join(env_content_to_add))

            print_colored(f"  ✅ Updated {env_file}", Colors.GREEN)
        else:
            print_colored(f"  ⚠️  .env file not found: {env_file}", Colors.YELLOW)
            print_colored(f"     You may need to create it from .env.example", Colors.YELLOW)

        return True

    except Exception as e:
        print_colored(f"  ⚠️  Could not update .env file: {e}", Colors.YELLOW)
        return True  # Non-critical


def main():
    parser = argparse.ArgumentParser(
        description='Setup custom nodes mounts for Dify',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog='''
Examples:
  # Docker mode
  %(prog)s --target ../dify --patcher-root . --mode docker

  # Development mode
  %(prog)s --target ../dify --patcher-root . --mode dev --force
        '''
    )

    parser.add_argument(
        '--target',
        required=True,
        type=Path,
        help='Target Dify directory'
    )

    parser.add_argument(
        '--patcher-root',
        required=True,
        type=Path,
        help='Dify-patcher root directory'
    )

    parser.add_argument(
        '--mode',
        choices=['docker', 'dev'],
        default='docker',
        help='Installation mode (default: docker)'
    )

    parser.add_argument(
        '--force',
        action='store_true',
        help='Force overwrite existing symlinks (dev mode only)'
    )

    args = parser.parse_args()

    # Resolve paths
    target_dir = args.target.resolve()
    patcher_root = args.patcher_root.resolve()

    # Validate directories
    if not target_dir.exists():
        print_colored(f"❌ Target directory not found: {target_dir}", Colors.RED)
        return 1

    if not patcher_root.exists():
        print_colored(f"❌ Patcher root directory not found: {patcher_root}", Colors.RED)
        return 1

    # Setup based on mode
    if args.mode == 'docker':
        success = setup_docker_mode(target_dir, patcher_root)
    else:  # dev mode
        success = setup_dev_mode(target_dir, patcher_root, args.force)

    if success:
        print()
        print_colored("✅ Mount setup complete!", Colors.GREEN)
        return 0
    else:
        print()
        print_colored("❌ Mount setup failed", Colors.RED)
        return 1


if __name__ == '__main__':
    sys.exit(main())
